from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import (
    KitVariantsAPI,
    MyCollectionAPI,
    MyCollectionDetailAPI,
    PublicUserKitDetailAPI,
    ExploreKitsAPI,
    FollowingFeedAPI,
    UserCollectionAPI,
    KitCatalogAPI, 
    KitOptionsView,
    TeamSearchAPI,
    TeamResolveAPI,
    AdminKitTypeSuggestionsAPI,
    AdminKitTypeModerationActionsAPI,
    AdminKitTypeModerationActionUndoAPI,
    AdminTeamSeasonKitTypeApproveAPI,
    AdminTeamSeasonKitTypeRejectAPI,
    AdminTeamSeasonKitTypeMergeAPI,
    AdminUnverifiedTeamsAPI,
    AdminCountriesAPI,
    AdminLeaguesAPI,
    AdminCatalogCountriesAPI,
    AdminCatalogCountryDetailAPI,
    AdminCatalogLeaguesAPI,
    AdminCatalogLeagueDetailAPI,
    AdminCatalogTeamsAPI,
    AdminCatalogTeamDetailAPI,
    AdminTeamApproveAPI,
    AdminTeamMergeAPI,
    AdminTeamRejectAPI,
    AdminTeamDeleteContentAPI,
    UserCollectionStatsAPI,
    MyCollectionValueHistoryAPI,
    MyWishlistAPI,
    UserWishlistAPI,
    WishlistDetailAPI,
    WishlistToggleAPI,
    UserSearchAPI,
    KitSearchSuggestionsAPI,
    ConversationListAPI,
    StartConversationAPI,
    ConversationDetailAPI,
    ConversationMessagesAPI,
    UnreadMessagesCountAPI,
    NotificationListAPI,
    NotificationUnreadCountAPI,
    MarkNotificationsReadAPI,
    UpdateProfileView,
    CurrentUserAPI,
    ToggleLikeAPI,
    KitCommentsAPI,
    ReplyToCommentAPI,
    ToggleCommentLikeAPI,
    DeleteCommentAPI,
    ReportKitAPI,
    LeagueListAPI,
    TeamsByLeagueAPI,
    TopKitsByTeamAPI,
    ApprovedTeamSeasonKitTypesAPI,
    CheckUsernameAPI,
    CountryListView,
    ToggleFollowView,
    FollowersListAPI,
    FollowingListAPI,
    KitLikersListAPI,
)
from .views_auth import GoogleLogin


urlpatterns = [
    path('my-collection/', MyCollectionAPI.as_view(), name='api-my-collection'),
    path('my-collection/<int:pk>/', MyCollectionDetailAPI.as_view(), name='api-my-collection-detail'),
    path('catalog/', KitCatalogAPI.as_view(), name='api-catalog'),
    path('explore/kits/', ExploreKitsAPI.as_view(), name='explore-kits'),
    path('feed/following/', FollowingFeedAPI.as_view(), name='following-feed'),
    path('user-collection/<str:username>/', UserCollectionAPI.as_view(), name='api-user-collection'),
    path('auth/google/', GoogleLogin.as_view(), name='google_login'),
    path('options/', KitOptionsView.as_view(), name='kit-options'),
    path('teams/search/', TeamSearchAPI.as_view(), name='team-search'),
    path('teams/<str:team_identifier>/resolve/', TeamResolveAPI.as_view(), name='team-resolve'),
    path('admin/kit-type-suggestions/', AdminKitTypeSuggestionsAPI.as_view(), name='admin-kit-type-suggestions'),
    path('admin/kit-type-moderation-actions/', AdminKitTypeModerationActionsAPI.as_view(), name='admin-kit-type-moderation-actions'),
    path('admin/kit-type-moderation-actions/<int:pk>/undo/', AdminKitTypeModerationActionUndoAPI.as_view(), name='admin-kit-type-moderation-action-undo'),
    path('admin/team-season-kit-types/<int:pk>/approve/', AdminTeamSeasonKitTypeApproveAPI.as_view(), name='admin-team-season-kit-type-approve'),
    path('admin/team-season-kit-types/<int:pk>/reject/', AdminTeamSeasonKitTypeRejectAPI.as_view(), name='admin-team-season-kit-type-reject'),
    path('admin/team-season-kit-types/<int:pk>/merge/', AdminTeamSeasonKitTypeMergeAPI.as_view(), name='admin-team-season-kit-type-merge'),
    path('admin/teams/unverified/', AdminUnverifiedTeamsAPI.as_view(), name='admin-unverified-teams'),
    path('admin/countries/', AdminCountriesAPI.as_view(), name='admin-countries'),
    path('admin/leagues/', AdminLeaguesAPI.as_view(), name='admin-leagues'),
    path('admin/catalog/countries/', AdminCatalogCountriesAPI.as_view(), name='admin-catalog-countries'),
    path('admin/catalog/countries/<int:pk>/', AdminCatalogCountryDetailAPI.as_view(), name='admin-catalog-country-detail'),
    path('admin/catalog/leagues/', AdminCatalogLeaguesAPI.as_view(), name='admin-catalog-leagues'),
    path('admin/catalog/leagues/<int:pk>/', AdminCatalogLeagueDetailAPI.as_view(), name='admin-catalog-league-detail'),
    path('admin/catalog/teams/', AdminCatalogTeamsAPI.as_view(), name='admin-catalog-teams'),
    path('admin/catalog/teams/<int:pk>/', AdminCatalogTeamDetailAPI.as_view(), name='admin-catalog-team-detail'),
    path('admin/teams/<int:team_id>/approve/', AdminTeamApproveAPI.as_view(), name='admin-team-approve'),
    path('admin/teams/<int:team_id>/merge/', AdminTeamMergeAPI.as_view(), name='admin-team-merge'),
    path('admin/teams/<int:team_id>/reject/', AdminTeamRejectAPI.as_view(), name='admin-team-reject'),
    path('admin/teams/<int:team_id>/delete-content/', AdminTeamDeleteContentAPI.as_view(), name='admin-team-delete-content'),
    path('search/kits/', KitSearchSuggestionsAPI.as_view(), name='kit-search-suggestions'),
    path('user-stats/<str:username>/', UserCollectionStatsAPI.as_view(), name='user-stats'),
    path('me/collection-value-history/', MyCollectionValueHistoryAPI.as_view(), name='my-collection-value-history'),
    path('me/wishlist/', MyWishlistAPI.as_view(), name='my-wishlist'),
    path('users/<str:username>/wishlist/', UserWishlistAPI.as_view(), name='user-wishlist'),
    path('wishlist/toggle/', WishlistToggleAPI.as_view(), name='wishlist-toggle'),
    path('wishlist/<int:pk>/', WishlistDetailAPI.as_view(), name='wishlist-detail'),
    path('users/search/', UserSearchAPI.as_view(), name='user-search'),
    path('conversations/', ConversationListAPI.as_view(), name='conversation-list'),
    path('conversations/start/', StartConversationAPI.as_view(), name='conversation-start'),
    path('conversations/unread-count/', UnreadMessagesCountAPI.as_view(), name='conversation-unread-count'),
    path('conversations/<int:conversation_id>/', ConversationDetailAPI.as_view(), name='conversation-detail'),
    path('conversations/<int:conversation_id>/messages/', ConversationMessagesAPI.as_view(), name='conversation-messages'),
    path('notifications/', NotificationListAPI.as_view(), name='notification-list'),
    path('notifications/unread-count/', NotificationUnreadCountAPI.as_view(), name='notification-unread-count'),
    path('notifications/mark-read/', MarkNotificationsReadAPI.as_view(), name='notification-mark-read'),
    path('profile/update/', UpdateProfileView.as_view(), name='update-profile'),
    path('auth/user/', CurrentUserAPI.as_view(), name='current-user'),
    path('kits/<int:userkit_id>/', PublicUserKitDetailAPI.as_view(), name='kit-detail'),
    path('kits/<int:pk>/like/', ToggleLikeAPI.as_view(), name='toggle-like'),
    path('kits/<int:userkit_id>/report/', ReportKitAPI.as_view(), name='kit-report'),
    path('kits/<int:userkit_id>/comments/', KitCommentsAPI.as_view(), name='kit-comments'),
    path('comments/<int:comment_id>/reply/', ReplyToCommentAPI.as_view(), name='comment-reply'),
    path('comments/<int:comment_id>/like/', ToggleCommentLikeAPI.as_view(), name='comment-like'),
    path('comments/<int:comment_id>/', DeleteCommentAPI.as_view(), name='comment-delete'),
    path('leagues/', LeagueListAPI.as_view(), name='league-list'),
    path('teams/league/<int:league_id>/', TeamsByLeagueAPI.as_view(), name='teams-by-league'),
    path('kits/team/<int:team_id>/best/', TopKitsByTeamAPI.as_view(), name='top-kits-by-team'),
    path('teams/<int:team_id>/approved-kit-types/', ApprovedTeamSeasonKitTypesAPI.as_view(), name='approved-team-season-kit-types'),
    path('auth/check-username/', CheckUsernameAPI.as_view(), name='check-username'),
    path('countries/', CountryListView.as_view(), name='country-list'),
    path('users/<str:username>/follow/', ToggleFollowView.as_view(), name='toggle-follow'),
    path('kits/team/<str:team_identifier>/variants/', KitVariantsAPI.as_view(), name='kit-variants'),
    path('users/<str:username>/followers/', FollowersListAPI.as_view(), name='user-followers'),
    path('users/<str:username>/following/', FollowingListAPI.as_view(), name='user-following'),
    path('kits/<int:kit_id>/likers/', KitLikersListAPI.as_view(), name='kit-likers'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
