from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import (
    KitVariantsAPI,
    MyCollectionAPI,
    MyCollectionDetailAPI,
    PublicUserKitDetailAPI,
    UserCollectionAPI,
    KitCatalogAPI, 
    KitOptionsView,
    TeamSearchAPI,
    UserCollectionStatsAPI,
    UserSearchAPI,
    ConversationListAPI,
    StartConversationAPI,
    ConversationDetailAPI,
    ConversationMessagesAPI,
    UnreadMessagesCountAPI,
    UpdateProfileView,
    CurrentUserAPI,
    ToggleLikeAPI,
    KitCommentsAPI,
    ReplyToCommentAPI,
    ToggleCommentLikeAPI,
    DeleteCommentAPI,
    ReportKitAPI,
    LeagueListAPI,
    TeamsByLeagueAPI,
    TopKitsByTeamAPI,
    CheckUsernameAPI,
    CountryListView,
    ToggleFollowView,
    FollowersListAPI,
    FollowingListAPI,
    KitLikersListAPI,
)
from .views_auth import GoogleLogin


urlpatterns = [
    path('my-collection/', MyCollectionAPI.as_view(), name='api-my-collection'),
    path('my-collection/<int:pk>/', MyCollectionDetailAPI.as_view(), name='api-my-collection-detail'),
    path('catalog/', KitCatalogAPI.as_view(), name='api-catalog'),
    path('user-collection/<str:username>/', UserCollectionAPI.as_view(), name='api-user-collection'),
    path('auth/google/', GoogleLogin.as_view(), name='google_login'),
    path('options/', KitOptionsView.as_view(), name='kit-options'),
    path('teams/search/', TeamSearchAPI.as_view(), name='team-search'),
    path('user-stats/<str:username>/', UserCollectionStatsAPI.as_view(), name='user-stats'),
    path('users/search/', UserSearchAPI.as_view(), name='user-search'),
    path('conversations/', ConversationListAPI.as_view(), name='conversation-list'),
    path('conversations/start/', StartConversationAPI.as_view(), name='conversation-start'),
    path('conversations/unread-count/', UnreadMessagesCountAPI.as_view(), name='conversation-unread-count'),
    path('conversations/<int:conversation_id>/', ConversationDetailAPI.as_view(), name='conversation-detail'),
    path('conversations/<int:conversation_id>/messages/', ConversationMessagesAPI.as_view(), name='conversation-messages'),
    path('profile/update/', UpdateProfileView.as_view(), name='update-profile'),
    path('auth/user/', CurrentUserAPI.as_view(), name='current-user'),
    path('kits/<int:userkit_id>/', PublicUserKitDetailAPI.as_view(), name='kit-detail'),
    path('kits/<int:pk>/like/', ToggleLikeAPI.as_view(), name='toggle-like'),
    path('kits/<int:userkit_id>/report/', ReportKitAPI.as_view(), name='kit-report'),
    path('kits/<int:userkit_id>/comments/', KitCommentsAPI.as_view(), name='kit-comments'),
    path('comments/<int:comment_id>/reply/', ReplyToCommentAPI.as_view(), name='comment-reply'),
    path('comments/<int:comment_id>/like/', ToggleCommentLikeAPI.as_view(), name='comment-like'),
    path('comments/<int:comment_id>/', DeleteCommentAPI.as_view(), name='comment-delete'),
    path('leagues/', LeagueListAPI.as_view(), name='league-list'),
    path('teams/league/<int:league_id>/', TeamsByLeagueAPI.as_view(), name='teams-by-league'),
    path('kits/team/<int:team_id>/best/', TopKitsByTeamAPI.as_view(), name='top-kits-by-team'),
    path('auth/check-username/', CheckUsernameAPI.as_view(), name='check-username'),
    path('countries/', CountryListView.as_view(), name='country-list'),
    path('users/<str:username>/follow/', ToggleFollowView.as_view(), name='toggle-follow'),
    path('kits/team/<int:team_id>/variants/', KitVariantsAPI.as_view(), name='kit-variants'),
    path('users/<str:username>/followers/', FollowersListAPI.as_view(), name='user-followers'),
    path('users/<str:username>/following/', FollowingListAPI.as_view(), name='user-following'),
    path('kits/<int:kit_id>/likers/', KitLikersListAPI.as_view(), name='kit-likers'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
