# Generated by Django 6.0 on 2025-12-21 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='team_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=20)),
                ('kit_type', models.CharField(max_length=50)),
                ('estimated_price', models.DecimalField(decimal_places=2, default=0, help_text='Estimated price in $ (Size L in Very Good condition)', max_digits=10)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='kit_images/')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kits', to='kits.team')),
            ],
        ),
        migrations.CreateModel(
            name='UserKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shirt_technology', models.CharField(choices=[('PLAYER_ISSUE', 'Player Issue'), ('REPLICA', 'Replica'), ('MATCH_WORN', 'Match Worn')], max_length=20)),
                ('condition', models.CharField(choices=[('BNWT', 'Brand New With Tags'), ('MINT', 'New Without Tags'), ('VERY_GOOD', 'Very Good'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], max_length=20)),
                ('size', models.CharField(max_length=10)),
                ('for_sale', models.BooleanField(default=False)),
                ('manual_value', models.DecimalField(blank=True, decimal_places=2, help_text='Set your own value for the kit. If empty, the system will calculate it automatically.', max_digits=10, null=True)),
                ('final_value', models.DecimalField(decimal_places=2, default=0, help_text='Final value of the kit, either manual or calculated.', max_digits=10)),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_by', to='kits.kit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserKitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user_kits/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='kits.userkit')),
            ],
        ),
    ]
