# Generated by Django 5.2.9 on 2026-01-02 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit',
            name='kit_type',
            field=models.CharField(help_text='e.g., Home, Away, Third', max_length=50),
        ),
        migrations.AlterField(
            model_name='kit',
            name='season',
            field=models.CharField(help_text='e.g., 2021/2022', max_length=20),
        ),
        migrations.AlterField(
            model_name='userkit',
            name='size',
            field=models.CharField(choices=[('KIDS', 'Kids'), ('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large'), ('XXXL', 'Triple Extra Large')], max_length=10),
        ),
    ]
