# Generated by Django 5.2.9 on 2026-01-07 17:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0005_profile_is_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='userkit',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userkit',
            name='condition',
            field=models.CharField(choices=[('BNWT', 'Brand New With Tags'), ('MINT', 'New Without Tags'), ('VERY_GOOD', 'Very Good Condition'), ('GOOD', 'Good Condition'), ('FAIR', 'Fair Condition'), ('POOR', 'Poor Condition')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userkit',
            name='size',
            field=models.CharField(choices=[('KIDS', 'Kids'), ('XS', 'Extra Small (XS)'), ('S', 'Small (S)'), ('M', 'Medium (M)'), ('L', 'Large (L)'), ('XL', 'Extra Large (XL)'), ('XXL', 'Double Extra Large (XXL)'), ('XXXL', 'Triple Extra Large (XXXL)')], max_length=10),
        ),
    ]
