# Generated by Django 5.2.9 on 2026-01-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0006_userkit_added_at_alter_userkit_condition_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userkitimage',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='userkitimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
