# Generated by Django 5.2.9 on 2026-01-09 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0007_alter_userkitimage_options_userkitimage_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profile_avatars/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
