# Generated by Django 5.2.9 on 2026-01-12 09:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0008_profile_avatar_profile_bio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userkit',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_kits', to=settings.AUTH_USER_MODEL),
        ),
    ]
