# Generated by Django 5.2.9 on 2026-01-12 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0009_userkit_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userkit',
            name='player_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userkit',
            name='player_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
