# Generated by Django 5.2.9 on 2026-01-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0010_userkit_player_name_userkit_player_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userkit',
            name='offer_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
