# Generated by Django 5.2.9 on 2026-01-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0014_league_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkit',
            name='offer_link',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
