# Generated by Django 5.2.9 on 2026-01-21 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0015_alter_userkit_offer_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='kits.country'),
        ),
        migrations.AddField(
            model_name='profile',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar (USD)'), ('EUR', 'Euro (EUR)'), ('GBP', 'British Pound (GBP)')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fans', to='kits.team'),
        ),
        migrations.AddField(
            model_name='profile',
            name='has_changed_username',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram_link',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='on_vacation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_size',
            field=models.CharField(blank=True, choices=[('KIDS', 'Kids'), ('XS', 'Extra Small (XS)'), ('S', 'Small (S)'), ('M', 'Medium (M)'), ('L', 'Large (L)'), ('XL', 'Extra Large (XL)'), ('XXL', 'Double Extra Large (XXL)'), ('XXXL', 'Triple Extra Large (XXXL)')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='surname',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='tiktok_link',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_link',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='youTube_link',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
