# Generated by Django 5.2.9 on 2026-01-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0016_profile_country_profile_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_public',
        ),
        migrations.AddField(
            model_name='profile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='depop_link',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ebay_link',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook_link',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='vinted_link',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='website_link',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
