# Generated by Django 5.2.9 on 2026-03-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0018_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='userkit',
            name='in_the_collection',
            field=models.BooleanField(default=True),
        ),
    ]
