# Generated by Django 5.2.9 on 2026-05-30 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0020_kitcomment_kitcommentlike'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KitReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('wrong_team', 'Wrong team'), ('wrong_season', 'Wrong season'), ('wrong_kit_type', 'Wrong kit type'), ('wrong_details', 'Wrong details'), ('fake_or_misleading', 'Fake or misleading'), ('prohibited_content', 'Prohibited content'), ('spam', 'Spam'), ('harassment_or_abuse', 'Harassment or abuse'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('dismissed', 'Dismissed'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('resolution_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='kits.userkit')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kit_reports', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_kit_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('kit', 'reporter'), name='unique_kit_report_per_user')],
            },
        ),
    ]
