# Generated by Django 5.2.9 on 2026-06-01 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0022_conversation_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitcomment',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_replies', to='kits.kitcomment'),
        ),
    ]
