# Generated by Django 5.2.9 on 2026-06-03 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0023_kitcomment_reply_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('kit_like', 'Kit like'), ('follow', 'Follow')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_sent', to=settings.AUTH_USER_MODEL)),
                ('kit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='kits.userkit')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['recipient', 'read_at', '-created_at', '-id'], name='kits_notifi_recipie_db917a_idx'), models.Index(fields=['recipient', 'type', '-created_at', '-id'], name='kits_notifi_recipie_40facd_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('kit__isnull', False), ('type', 'kit_like')), fields=('recipient', 'actor', 'type', 'kit'), name='unique_kit_like_notification'), models.UniqueConstraint(condition=models.Q(('kit__isnull', True), ('type', 'follow')), fields=('recipient', 'actor', 'type'), name='unique_follow_notification')],
            },
        ),
    ]
