# Generated by Django 5.2.9 on 2026-06-03 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0024_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='kits.kitcomment'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('kit_like', 'Kit like'), ('follow', 'Follow'), ('kit_comment', 'Kit comment'), ('comment_like', 'Comment like'), ('comment_reply', 'Comment reply')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('comment__isnull', False), ('type__in', ['kit_comment', 'comment_like', 'comment_reply'])), fields=('recipient', 'actor', 'type', 'comment'), name='unique_comment_notification'),
        ),
    ]
