# Generated by Django 5.2.9 on 2026-06-04 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0025_notification_comment_alter_notification_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionValueSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('kits_count', models.PositiveIntegerField(default=0)),
                ('reason', models.CharField(choices=[('initial', 'Initial'), ('kit_added', 'Kit added'), ('kit_removed', 'Kit removed'), ('kit_updated', 'Kit updated'), ('value_updated', 'Value updated'), ('collection_status_changed', 'Collection status changed'), ('backfill', 'Backfill')], max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_userkit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kits.userkit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_value_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='kits_collec_user_id_be5cc7_idx'), models.Index(fields=['user', 'id'], name='kits_collec_user_id_881854_idx')],
            },
        ),
    ]
