# Generated by Django 5.2.9 on 2026-06-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0026_collectionvaluesnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='userkit',
            name='private_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
