# Generated by Django 5.2.9 on 2026-06-05 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0027_userkit_private_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=20)),
                ('kit_type', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_userkit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wishlist_references', to='kits.userkit')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='kits.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='kits_wishli_user_id_7d8e6f_idx'), models.Index(fields=['team', 'season', 'kit_type'], name='kits_wishli_team_id_06e58f_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'team', 'season', 'kit_type'), name='unique_user_wishlist_variant')],
            },
        ),
    ]
