# Generated by Django 5.2.9 on 2026-06-06 23:36

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone
from django.utils.text import slugify


KIT_TYPES = [
    ('Home', 'home', 'HOME', 'outfield', 'primary', 10),
    ('Away', 'away', 'AWAY', 'outfield', 'primary', 20),
    ('Third', 'third', 'THIRD', 'outfield', 'primary', 30),
    ('Fourth', 'fourth', 'FOURTH', 'outfield', 'expanded', 40),
    ('Cup', 'cup', 'CUP', 'competition', 'expanded', 50),
    ('Training', 'training', 'TRAINING', 'training', 'expanded', 60),
    ('Goalkeeper', 'goalkeeper', 'GOALKEEPER', 'goalkeeper', 'primary', 70),
    ('Second Goalkeeper', 'second-goalkeeper', 'SECOND_GOALKEEPER', 'goalkeeper', 'expanded', 80),
    ('Third Goalkeeper', 'third-goalkeeper', 'THIRD_GOALKEEPER', 'goalkeeper', 'expanded', 90),
    ('Special', 'special', 'SPECIAL', 'special', 'expanded', 100),
    ('Anniversary', 'anniversary', 'ANNIVERSARY', 'special', 'none', 110),
    ('Pre-match', 'pre-match', 'PRE_MATCH', 'training', 'none', 120),
    ('Warm-up', 'warm-up', 'WARM_UP', 'training', 'none', 130),
    ('European', 'european', 'EUROPEAN', 'competition', 'none', 140),
    ('Final', 'final', 'FINAL', 'competition', 'none', 150),
    ('Charity', 'charity', 'CHARITY', 'special', 'none', 160),
    ('Commemorative', 'commemorative', 'COMMEMORATIVE', 'special', 'none', 170),
    ('Retro/Reissue', 'retro-reissue', 'RETRO_REISSUE', 'special', 'none', 180),
]

KIT_TYPE_ALIASES = [
    ('gk', 'GOALKEEPER'),
    ('goalkeeper', 'GOALKEEPER'),
    ('keeper', 'GOALKEEPER'),
    ('goalie', 'GOALKEEPER'),
    ('second goalkeeper', 'SECOND_GOALKEEPER'),
    ('2nd goalkeeper', 'SECOND_GOALKEEPER'),
    ('second gk', 'SECOND_GOALKEEPER'),
    ('2nd gk', 'SECOND_GOALKEEPER'),
    ('third goalkeeper', 'THIRD_GOALKEEPER'),
    ('3rd goalkeeper', 'THIRD_GOALKEEPER'),
    ('third gk', 'THIRD_GOALKEEPER'),
    ('3rd gk', 'THIRD_GOALKEEPER'),
    ('special edition', 'SPECIAL'),
    ('special', 'SPECIAL'),
    ('pre match', 'PRE_MATCH'),
    ('prematch', 'PRE_MATCH'),
    ('pre-match', 'PRE_MATCH'),
    ('warm up', 'WARM_UP'),
    ('warm-up', 'WARM_UP'),
    ('reissue', 'RETRO_REISSUE'),
    ('retro', 'RETRO_REISSUE'),
    ('retro reissue', 'RETRO_REISSUE'),
    ('european', 'EUROPEAN'),
    ('europe', 'EUROPEAN'),
    ('champions league', 'EUROPEAN'),
    ('final', 'FINAL'),
    ('charity', 'CHARITY'),
    ('commemorative', 'COMMEMORATIVE'),
]

SHIRT_VERSIONS = [
    ('UNSPECIFIED', 'Not specified', Decimal('1.000'), False, 10),
    ('REPLICA', 'Replica', Decimal('1.000'), False, 20),
    ('SUPPORTER', 'Stadium', Decimal('1.000'), False, 30),
    ('AUTHENTIC', 'Authentic', Decimal('1.000'), False, 40),
    ('TEAM_ISSUED', 'Team Issued', Decimal('1.000'), True, 50),
    ('PLAYER_ISSUE', 'Player Issue', Decimal('1.500'), False, 60),
    ('MATCH_ISSUE', 'Match Issue', Decimal('1.000'), True, 70),
    ('MATCH_PREPARED', 'Match Prepared', Decimal('1.000'), True, 80),
    ('MATCH_WORN', 'Match Worn', Decimal('5.000'), True, 90),
    ('TRAINING_ISSUE', 'Training Issue', Decimal('1.000'), True, 100),
    ('SAMPLE', 'Sample', Decimal('1.000'), True, 110),
    ('PROTOTYPE', 'Prototype', Decimal('1.000'), True, 120),
]


def normalize_type_name(value):
    return ' '.join((value or '').strip().lower().split())


def get_unique_slug(KitType, name):
    base_slug = slugify(name) or 'kit-type'
    candidate = base_slug
    suffix = 2
    while KitType.objects.filter(slug=candidate).exists():
        candidate = f'{base_slug}-{suffix}'
        suffix += 1
    return candidate


def seed_and_backfill_catalogs(apps, schema_editor):
    Kit = apps.get_model('kits', 'Kit')
    KitType = apps.get_model('kits', 'KitType')
    KitTypeAlias = apps.get_model('kits', 'KitTypeAlias')
    ShirtVersion = apps.get_model('kits', 'ShirtVersion')
    UserKit = apps.get_model('kits', 'UserKit')
    WishlistItem = apps.get_model('kits', 'WishlistItem')
    approved_at = timezone.now()

    kit_types_by_code = {}
    for name, slug, code, category, visibility, sort_order in KIT_TYPES:
        kit_type, _ = KitType.objects.update_or_create(
            canonical_code=code,
            defaults={
                'name': name,
                'slug': slug,
                'category': category,
                'status': 'approved',
                'default_visibility': visibility,
                'sort_order': sort_order,
                'approved_at': approved_at,
            },
        )
        kit_types_by_code[code] = kit_type

    for alias, code in KIT_TYPE_ALIASES:
        KitTypeAlias.objects.update_or_create(
            alias_normalized=normalize_type_name(alias),
            defaults={
                'kit_type': kit_types_by_code[code],
                'display_alias': alias,
            },
        )

    versions_by_code = {}
    for code, name, multiplier, manual_recommended, sort_order in SHIRT_VERSIONS:
        version, _ = ShirtVersion.objects.update_or_create(
            code=code,
            defaults={
                'name': name,
                'valuation_multiplier': multiplier,
                'manual_value_recommended': manual_recommended,
                'sort_order': sort_order,
                'is_active': True,
            },
        )
        versions_by_code[code] = version

    aliases_by_name = {
        alias.alias_normalized: alias.kit_type
        for alias in KitTypeAlias.objects.select_related('kit_type').all()
    }
    types_by_name = {
        normalize_type_name(kit_type.name): kit_type
        for kit_type in KitType.objects.all()
    }

    def resolve_kit_type(raw_name):
        normalized_name = normalize_type_name(raw_name)
        if not normalized_name:
            return None
        resolved = aliases_by_name.get(normalized_name) or types_by_name.get(normalized_name)
        if resolved is not None:
            return resolved

        display_name = ' '.join((raw_name or '').strip().split())
        pending_type = KitType.objects.create(
            name=display_name,
            slug=get_unique_slug(KitType, display_name),
            category='other',
            status='pending',
            default_visibility='none',
            sort_order=1000,
        )
        types_by_name[normalized_name] = pending_type
        return pending_type

    for kit in Kit.objects.filter(kit_type_ref__isnull=True).only('id', 'kit_type'):
        resolved_type = resolve_kit_type(kit.kit_type)
        if resolved_type is not None:
            Kit.objects.filter(pk=kit.pk, kit_type_ref__isnull=True).update(kit_type_ref=resolved_type)

    for legacy_code in ('REPLICA', 'PLAYER_ISSUE', 'MATCH_WORN'):
        UserKit.objects.filter(
            shirt_version__isnull=True,
            shirt_technology=legacy_code,
        ).update(shirt_version=versions_by_code[legacy_code])

    for item in WishlistItem.objects.filter(kit_type_ref__isnull=True).only('id', 'kit_type'):
        resolved_type = resolve_kit_type(item.kit_type)
        if resolved_type is not None:
            WishlistItem.objects.filter(pk=item.pk, kit_type_ref__isnull=True).update(kit_type_ref=resolved_type)


def reverse_seed_and_backfill(apps, schema_editor):
    # The schema rollback removes the compatibility fields and catalog tables.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0028_wishlistitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShirtVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('valuation_multiplier', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=6)),
                ('manual_value_recommended', models.BooleanField(default=False)),
                ('valuation_note', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='KitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('canonical_code', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('category', models.CharField(choices=[('outfield', 'Outfield'), ('goalkeeper', 'Goalkeeper'), ('training', 'Training'), ('special', 'Special'), ('competition', 'Competition'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('merged', 'Merged')], default='pending', max_length=20)),
                ('default_visibility', models.CharField(choices=[('primary', 'Primary'), ('expanded', 'Expanded'), ('none', 'None')], default='none', max_length=20)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_kit_types', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_kit_types', to=settings.AUTH_USER_MODEL)),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_types', to='kits.kittype')),
            ],
            options={
                'ordering': ['sort_order', 'name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='kit',
            name='kit_type_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kits', to='kits.kittype'),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='kit_type_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wishlist_items', to='kits.kittype'),
        ),
        migrations.CreateModel(
            name='KitTypeAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_normalized', models.CharField(max_length=120, unique=True)),
                ('display_alias', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_kit_type_aliases', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_kit_type_aliases', to=settings.AUTH_USER_MODEL)),
                ('kit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='kits.kittype')),
            ],
            options={
                'ordering': ['alias_normalized', 'id'],
            },
        ),
        migrations.AddField(
            model_name='userkit',
            name='shirt_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_kits', to='kits.shirtversion'),
        ),
        migrations.CreateModel(
            name='TeamSeasonKitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('source', models.CharField(choices=[('system_default', 'System default'), ('upload', 'Upload'), ('moderator', 'Moderator')], default='upload', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_team_season_kit_types', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_team_season_kit_types', to=settings.AUTH_USER_MODEL)),
                ('kit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_seasons', to='kits.kittype')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_kit_types', to='kits.team')),
            ],
            options={
                'ordering': ['team__name', '-season', 'kit_type__sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('team', 'season', 'kit_type'), name='unique_team_season_kit_type')],
            },
        ),
        migrations.RunPython(seed_and_backfill_catalogs, reverse_seed_and_backfill),
    ]
