# Generated by Django 5.2.9 on 2026-06-09 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0030_rename_supporter_version_to_stadium'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KitTypeModerationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('merge', 'Merge')], max_length=20)),
                ('team_name', models.CharField(blank=True, default='', max_length=100)),
                ('season', models.CharField(blank=True, default='', max_length=20)),
                ('source_kit_type_name', models.CharField(blank=True, default='', max_length=120)),
                ('target_kit_type_name', models.CharField(blank=True, default='', max_length=120)),
                ('previous_state', models.JSONField(blank=True, default=dict)),
                ('resulting_state', models.JSONField(blank=True, default=dict)),
                ('is_reversible', models.BooleanField(default=True)),
                ('undo_block_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('undone_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kit_type_moderation_actions', to=settings.AUTH_USER_MODEL)),
                ('source_kit_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_moderation_actions', to='kits.kittype')),
                ('target_kit_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_moderation_actions', to='kits.kittype')),
                ('team_season_kit_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to='kits.teamseasonkittype')),
                ('undone_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='undone_kit_type_moderation_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['created_at', 'id'], name='kits_kittyp_created_cda3e1_idx'), models.Index(fields=['action_type', 'created_at'], name='kits_kittyp_action__7aeef0_idx')],
            },
        ),
    ]
