# Generated by Django 5.2.9 on 2026-06-09 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0031_kittypemoderationaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamModerationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('approve', 'Approve'), ('merge', 'Merge'), ('reject', 'Reject')], max_length=20)),
                ('source_team_id_snapshot', models.IntegerField(blank=True, null=True)),
                ('source_team_name', models.CharField(blank=True, default='', max_length=100)),
                ('target_team_name', models.CharField(blank=True, default='', max_length=100)),
                ('previous_state', models.JSONField(blank=True, default=dict)),
                ('resulting_state', models.JSONField(blank=True, default=dict)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('is_reversible', models.BooleanField(default=False)),
                ('undo_block_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('undone_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_moderation_actions', to=settings.AUTH_USER_MODEL)),
                ('target_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_moderation_actions', to='kits.team')),
                ('undone_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='undone_team_moderation_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['created_at', 'id'], name='kits_teammo_created_3a7366_idx'), models.Index(fields=['action_type', 'created_at'], name='kits_teammo_action__197724_idx')],
            },
        ),
    ]
