# Generated by Django 5.2.9 on 2026-06-10 10:23

from collections import Counter

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def assert_country_name_casefold_uniqueness(apps, schema_editor):
    Country = apps.get_model('kits', 'Country')
    normalized_names = Counter(
        (country.name or '').strip().lower()
        for country in Country.objects.all().only('name')
    )
    duplicates = [name for name, count in normalized_names.items() if name and count > 1]
    if duplicates:
        raise RuntimeError(
            'Cannot add case-insensitive country-name uniqueness because duplicate rows already exist: '
            + ', '.join(sorted(duplicates))
        )


def backfill_team_country_from_league_country(apps, schema_editor):
    Team = apps.get_model('kits', 'Team')
    rows = list(
        Team.objects.filter(
            country__isnull=True,
            league__isnull=False,
            league__country__isnull=False,
        ).select_related('league__country')
    )
    for team in rows:
        team.country_id = team.league.country_id
    if rows:
        Team.objects.bulk_update(rows, ['country'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0032_teammoderationaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='country',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_countries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='country',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='league',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='league',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leagues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='league',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='team',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='kits.country'),
        ),
        migrations.RunPython(assert_country_name_casefold_uniqueness, noop_reverse),
        migrations.RunPython(backfill_team_country_from_league_country, noop_reverse),
        migrations.AddConstraint(
            model_name='country',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='kits_country_name_ci_unique'),
        ),
    ]
