# Generated by Django 5.2.9 on 2026-06-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0033_country_code_country_created_at_country_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammoderationaction',
            name='action_type',
            field=models.CharField(choices=[('approve', 'Approve'), ('merge', 'Merge'), ('reject', 'Reject'), ('delete_content', 'Delete content')], max_length=20),
        ),
    ]
