# Generated by Django 5.2.9 on 2026-06-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0034_alter_teammoderationaction_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_collection_value_publicly',
            field=models.BooleanField(default=False),
        ),
    ]
