# Generated by Django 5.2.9 on 2026-06-13 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0035_profile_show_collection_value_publicly'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userkit',
            name='hidden_by_moderation_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userkit',
            name='hidden_by_moderation_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_hidden_userkits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userkit',
            name='is_hidden_by_moderation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userkit',
            name='moderation_hidden_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('kit_like', 'Kit like'), ('follow', 'Follow'), ('kit_comment', 'Kit comment'), ('comment_like', 'Comment like'), ('comment_reply', 'Comment reply'), ('moderation_kit_removed', 'Moderation kit removed')], max_length=32),
        ),
        migrations.CreateModel(
            name='KitReportModerationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('dismiss', 'Dismiss'), ('remove_kit', 'Remove kit')], max_length=20)),
                ('report_ids', models.JSONField(blank=True, default=list)),
                ('previous_state', models.JSONField(blank=True, default=dict)),
                ('resulting_state', models.JSONField(blank=True, default=dict)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kit_report_moderation_actions', to=settings.AUTH_USER_MODEL)),
                ('kit_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_kit_report_moderation_actions', to=settings.AUTH_USER_MODEL)),
                ('userkit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_moderation_actions', to='kits.userkit')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['action_type', 'created_at'], name='kits_kitrep_action__f08766_idx'), models.Index(fields=['created_at', 'id'], name='kits_kitrep_created_152717_idx')],
            },
        ),
    ]
