# Generated by Django 5.2.9 on 2026-06-13 17:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0036_userkit_hidden_by_moderation_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userkit',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userkit',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
